kind: pipeline
type: docker
name: carrot-before-pr-merged

trigger:
  event:
    - pull_request
  action:
    - opened
    - reopened
    - synchronize

steps:
- name: first-ci-step
  image: alpine
  commands:
  - echo hello
  - echo before1

- name: second-ci-step
  image: alpine
  commands:
    - echo hello
    - echo before2

---
kind: pipeline
type: docker
name: carrot-after-pr-merged

trigger:
  branch:
    - master
  event:
    - push

steps:
  - name: ecr_push
    image: alpine
    commands:
      - echo hello
      - echo after